#!/usr/bin/env python3
"""Write audit/private_gap_holds.md: every private-gap candidate still on HOLD.

A hold is a candidate the automated pass could not settle - a booking engine that
would not render, a human-check page that is not to be bypassed, an unconfirmed
pin, or a category/ownership question that is AWH's call. The source of truth is
each state's audit/<st>_private/verdicts.jsonl, where the LATEST row per name
wins; settling a hold means appending a new row (audit/private_gap_browser/v.py)
and, for an add, running append_state.py as usual. Re-run this script afterwards
to refresh the checklist.

    python3 audit/private_gap_holds.py
"""
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def lookup(state_dir):
    """name -> {city, website, phone} from the state's candidate files and its Google
    Maps lookups (google.json: rating, site, phone, pin per candidate)."""
    info = {}
    for path in ('candidates.json', 'work.json', 'google.json'):
        p = os.path.join(state_dir, path)
        if not os.path.exists(p):
            continue
        data = json.load(open(p))
        rows = data if isinstance(data, list) else [
            r for v in data.values() if isinstance(v, list) for r in v]
        for r in rows:
            if not isinstance(r, dict) or 'name' not in r:
                continue
            d = info.setdefault(r['name'], {})
            d.setdefault('city', r.get('city'))
            for k_src, k in (('g_site', 'website'), ('g_phone', 'phone'), ('url', 'rvlife')):
                if r.get(k_src):
                    d.setdefault(k, r[k_src])
    return info


def main():
    out = ["# Private gap - holds awaiting a human",
           "",
           "Generated by `audit/private_gap_holds.py` from the per-state `verdicts.jsonl` "
           "(latest row per name wins). Settle one by appending a verdict "
           "(`python3 audit/private_gap_browser/v.py <st>_private '<json>'`), adding it "
           "with `append_state.py` if it passes, then re-run this script.",
           "",
           "Gate reminder (docs/campground-curation.md): published base rate <= $50 for the "
           "cheapest hookup RV site on a peak-season weeknight, quality signal, live web "
           "presence, real transient campground (not membership/seasonal/truck-stop).",
           ""]
    total = 0
    for vf in sorted(glob.glob(os.path.join(HERE, '*_private', 'verdicts.jsonl'))):
        sdir = os.path.dirname(vf)
        st = os.path.basename(sdir).split('_')[0].upper()
        last = {}
        for line in open(vf):
            line = line.strip()
            if line:
                d = json.loads(line)
                last[d['name']] = d
        holds = [d for d in last.values() if d['decision'] == 'hold']
        if not holds:
            continue
        info = lookup(sdir)
        out += [f"## {st} ({len(holds)})", ""]
        for d in sorted(holds, key=lambda d: d['name'].lower()):
            i = info.get(d['name'], {})
            bits = [b for b in (i.get('city'), i.get('website'),
                                f"phone {i['phone']}" if i.get('phone') else None) if b]
            out.append(f"- [ ] **{d['name']}**" + (f" - {' | '.join(bits)}" if bits else ""))
            out.append(f"  - {d['why']}" + (f" (rate seen: ${d['base_rate']})" if d.get('base_rate') else ""))
        out.append("")
        total += len(holds)
    out.insert(2, f"**{total} open holds.**")
    out.insert(3, "")
    path = os.path.join(HERE, 'private_gap_holds.md')
    open(path, 'w').write("\n".join(out))
    print(f"{total} holds -> {path}")


if __name__ == '__main__':
    main()
